version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_db3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: callfone
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container3
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
volumes:
  mysql_data: